engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- app/assets/*
- "**/vendor/**/*"
- lib/assets/**/*
- solr/**/*
- db/**/*